FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y openjdk-11-jre-headless

COPY requirements-consumer.txt /

RUN pip install -r requirements-consumer.txt

COPY consumer.py /

#CMD ["python", "/consumer.py"]

CMD sleep infinity