version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:3"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    image: "bitnami/kafka:3"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    restart: on-failure
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=eth_block
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    volumes:
      - ./producer.py:/producer.py
    container_name: producer
    depends_on:
      - kafka
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./consumer.py:/consumer.py
    container_name: consumer
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=eth_block
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
    depends_on:
      - kafka
    restart: on-failure

volumes:
  influxdb_data:
